FROM python:3.8-slim

COPY utils/requirements.txt /requirements.txt
RUN apt update \
  && apt install -y build-essential \
  && pip3 install -r /requirements.txt \
  && apt autoremove -y build-essential \
  && rm -rf /root/.cache \
  && rm -rf /var/lib/apt/lists/*

COPY . /opt/iivr
COPY SGX_lib/libcSGX/IIV.signed.so /opt/iivr/IIV_app/IIV.signed.so

RUN apt update \
  && apt install -y curl build-essential libcurl4 libprotobuf-dev \
  && curl -o sgx_sdk.bin https://download.01.org/intel-sgx/linux-2.4/ubuntu18.04-server/sgx_linux_x64_sdk_2.4.100.48163.bin \
  && chmod +x sgx_sdk.bin \
  && ./sgx_sdk.bin --prefix /opt/intel/ \
  && cp -ra /opt/intel/sgxsdk/lib64/* /usr/lib/ \
  && cd /opt/iivr/SGX_lib \
  && python3 setup.py install \
  && apt autoremove -y curl build-essential libprotobuf-dev \
  && rm -rf /var/lib/apt/lists/*

ENV LD_LIBRARY_PATH /opt/iivr/SGX_lib/libcSGX
WORKDIR /opt/iivr/IIV_app
CMD [ "python3", "/opt/iivr/IIV_app/run.py" ]
